### ISSUE TITLE
STM32 Problems with keil uvision 5

### ISSUE THREAD

**Issue by sfranchin63** [kgabis/parson#100]
Hi,
I tried to insert in the uvision 5 the parson.c and parson.h but the test result is mistaken. 
The function:
-    json_object_dotset_string(root_object, "address.city", "Cupertino");
 -   json_object_dotset_value(root_object, "contact.emails", json_parse_string("[\"email@example.com\",\"email2@example.com\"]"));
aren't correct response.
![json 6](https://user-images.githubusercontent.com/23196408/39866286-5fa1a106-5450-11e8-9622-14e581fff7f0.JPG)
![seriale 6](https://user-images.githubusercontent.com/23196408/39866287-5fc098c2-5450-11e8-8da6-eaad06884a12.JPG)
 
For further infomation I enclose the prints and the serial output.
Can you help me?
Thanks

**Comment by kgabis** [comment]
I’m unable to replicate your issue. What are the contents of “serialized_string” immediately after calling json_serialize_to_string_pretty?

**Comment by sfranchin63** [comment]
The contents are those indicated in the two attached files. One display
the contents of the memory and in the other the printing on a serial
monitor. I think the problem may be in the dot. "contact.emails".
For example if I compile only the
json_object_set_string(root_object,"name","John Smith";
the  serialized_string  is {"name": "John Smith""}     look  the attached
file (json 1.jpg and seriale 1.jpg)
but if compile also
    json_object_set_string(root_object, "name", "John Smith");
    json_object_dotset_string(root_object, "address.city", "Cupertino");
    json_object_dotset_value(root_object, "contact.emails",
json_parse_string("[\"email@example.com\",\"email2@example.com\"]"));
the  serialized_string  is  :
{            "name": "John Smith",     "address": {}        } $ .. ecc.
 look seriale 6.jpg

Send you others ipg.
Thanks
Stefano


2018-05-10 13:17 GMT+02:00 Krzysztof Gabis <notifications@github.com>:

**Comment by kgabis** [comment]
No pictures are attached, please use webpage instead of replying to this email.
Are you using a custom allocator?

**Comment by sfranchin63** [comment]
![json 5](https://user-images.githubusercontent.com/23196408/39929380-3100a188-5538-11e8-9b94-6851a41af9ba.JPG)
![seriale 5](https://user-images.githubusercontent.com/23196408/39929396-37a32c86-5538-11e8-9f06-c8b95269bc91.JPG)
![json 4](https://user-images.githubusercontent.com/23196408/39929402-3b7730e6-5538-11e8-866e-50d0fd29e58c.JPG)
![seriale 4](https://user-images.githubusercontent.com/23196408/39929416-40f4b2a0-5538-11e8-91ee-bc47f7dbb159.JPG)
![json 3](https://user-images.githubusercontent.com/23196408/39929421-44e8f5ce-5538-11e8-8bcb-7487634c7ddf.JPG)
![seriale 3](https://user-images.githubusercontent.com/23196408/39929427-496827a0-5538-11e8-86ff-b0bdf14dc71e.JPG)

**Comment by mbelicki** [comment]
I would suggest to check value returned by `json_object_set_*` functions. My educated guess is that half way through `json_object_dotset_string(root_object, "address.city", "Cupertino");` allocation of required memory fails and the object gets only partially modified. After checking which function returns `JSON_Failure` first, you should be able to debug it to see what is the exact cause of this problem.

**Comment by kgabis** [comment]
@mbelicki was right (not for the first time).
I don't think this fixes your issue, but objects should no longer be left in incorrect state if  ```json_object_dotset_value``` fails. I think ```json_object_dotset_string(root_object, "address.city", "Cupertino");``` fails in some way (most likely on one of the allocations) but you'll have to provide me more data to help me debug it. Can you use breakpoints to debug control flow in ```json_object_dotset_value``` ?

**Comment by kgabis** [comment]
Thanks for sharing your conclusions :)
I'll close this issue, because I don't see any reasons to keep it open any longer.
