### ISSUE TITLE
Convert large strings to JSON_Value*

### ISSUE THREAD

**Issue by bkonno** [kgabis/parson#101]
I'm have been using for a long time the function **json_parse_string**, but now I need convert a large string (json array with 300 positions), the length is about 11k caracters, and the function return NULL. Is there any length limit to convert ?

**Comment by kgabis** [comment]
No there isn't, it should work. Can you provide the json string that makes it fail?

**Comment by bkonno** [comment]
[variation.txt](https://github.com/kgabis/parson/files/2188574/variation.txt)

txt file is attached and sometimes the length may be larger than that...

**Comment by kgabis** [comment]
I can parse this file without any problems, are you sure it’s not you memory allocator running out of memory and returning null?

**Comment by bkonno** [comment]
I realize that NULL come from function **parse_value**, in swith statement the "default" option return NULL.
