### ISSUE TITLE
errno in parse_number_value()

### ISSUE THREAD

**Issue by sharpie7** [kgabis/parson#108]
Thanks for a very useful library. One problem/question from me:

I am developing in a rather specialist embedded environment which disallows my module to read or write errno. The kernal and module loader I am having to work with seem to treat it as a memory violation.

In the library errno is used just once, in parse_number_value(), to check that strtod has worked. My question is: is there any need to check errno in that function? The only place it is called from is parse_value() which has already checked that there is a numeric value so strtod should always succeed.

I can obviously fork and remove the problematic errno reference for my application but how would you feel about removing it from the master?

**Comment by kgabis** [comment]
I'm afraid I can't remove that errno check because it's the only way to test for invalid value error (EINVAL, ERANGE can be checked by comparing result to +/- HUGE_VAL).

**Comment by sharpie7** [comment]
Thanks - I hadn't thought of that problem.
