### ISSUE TITLE
Making `parson_free` optional

### ISSUE THREAD

**Issue by woodruffw** [kgabis/parson#109]
First of all, thanks for writing `parson`!

Would a patch that makes `parson_free` optional be accepted? I'm using `parson` in an environment that uses a pool allocator, meaning that there is no "free" function as such -- all memory stays active until the pool that it belongs to is destroyed (or recycled).

Basically, I'd like to do this:

```c
json_set_allocation_functions(pool_malloc, NULL);
```

Let me know if the changes for that are something that you'd be willing to merge.

**Comment by kgabis** [comment]
Why not just create na free noop function and pass it as an argument to ```json_set_allocation_functions```?

e.g.
```c
void free_noop(void* ptr) { }
...
json_set_allocation_functions(pool_malloc, free_noop);
```

**Comment by woodruffw** [comment]
> Why not just create na free noop function and pass it as an argument to `json_set_allocation_functions`?

That's what I'm doing currently; I figured that it would make a slightly nicer interface to not require that no-op function. But it's minor, so I'll close this if you think adding it would be superfluous/add too much complexity to the interface.

**Comment by kgabis** [comment]
Passing a noop free function is quite obvious, you don't have to wonder whether passing a NULL will replace current free function with NULL, leave previous value assigned to it or make it a noop.
I'll close this issue since I can't see a good reason to have it :)
