### ISSUE TITLE
Comment support in JSON is bad idea

### ISSUE THREAD

**Issue by In-line** [kgabis/parson#111]
```json5
// This doesn't parse anymore!
[
  "foo",
  "bar",
//  "baz"
]
```

Consider using json5 or hjson specifications to resolve such problems.

https://github.com/alliedmodders/amxmodx/issues/683 (AMX Mod X uses parson in it's JSON implementation)

**Comment by In-line** [comment]
I have same opinion as in this comment https://github.com/kgabis/parson/issues/9#issuecomment-423293026

**Comment by kgabis** [comment]
Don't use ```*parse_with_comments``` functions then 🤷🏻‍♂️
