### ISSUE TITLE
json_serialize_to_string_pretty has no output when there are dotset in the object

### ISSUE THREAD

**Issue by jning8401** [kgabis/parson#112]
I tried an object with dotset string and number and cannot use json_serialize_to_string_pretty to print it. Tried json_serialize_to_string and json_serialize_to_buffer on the object, the output is correct in compact format.

Also tried an object with string and number, and json_serialize_to_string_pretty prints correctly. Do I miss anything here? Please advise. Thank you!

Example code (with sensitive data removed):
    JSON_Value *root_value = json_value_init_object();
    JSON_Object *root_object = json_value_get_object(root_value);

    char *serialized_string = NULL;

   json_object_dotset_string(root_object, "custom.variable1",
                                       custom_API());

    json_object_dotset_number(root_object, "custom.variable2",
                              custom_API2());
    char *buf = NULL;
    buf = json_serialize_to_string(root_value);
    printf(buf);

    char buf1[1100];
    status=json_serialize_to_buffer(root_value, buf1, 1100);

    printf(buf1);
    serialized_string = json_serialize_to_string_pretty(root_value);
    printf(serialized_string);

    json_free_serialized_string(serialized_string);
    json_free_serialized_string(buf);
    json_value_free(root_value);

**Comment by kgabis** [comment]
Please provide an example that I can compile to reproduce the issue.

**Comment by jning8401** [comment]
Thanks for the quick reply. It turned out to be issue with the customized printf in our codebase. It allows only 256 bytes. I use puts and it prints the output correctly. Problem solved and thanks!
