### ISSUE TITLE
Support case insensitive property name

### ISSUE THREAD

**Issue by troj-iii** [kgabis/parson#117]
Support for that:
treat `{"PropA": "val", "PropB": "val"}` same as `{"propa": "val", "propb": "val"}`.

Suggestion: just replace strcmp, strncmp with macros JSON_STRCMP, JSON_STRNCMP, and add a macro switch JSON_SUPPORT_CASE_INSENSITIVE for the expansion of compare MACROs.

**Comment by kgabis** [comment]
I don't think it's worth it. Case insensitive comparison of unicode characters is quite hard and I don't see why anyone would want it. Also, I haven't this this feature in any other JSON parser.
