### ISSUE TITLE
Example code vulnerable to command injection

### ISSUE THREAD

**Issue by oxr463** [kgabis/parson#122]
If user input is not properly validated, both `username`, and `repo` can be used to craft a command injection attack.

```c
    /* it ain't pretty, but it's not a libcurl tutorial */
    sprintf(curl_command, 
        "curl -s \"https://api.github.com/repos/%s/%s/commits\" > %s",
        username, repo, output_filename);
    sprintf(cleanup_command, "rm -f %s", output_filename);
    system(curl_command);
```
Source: https://github.com/kgabis/parson#parsing-json

Resources:

- https://www.owasp.org/index.php/Command_Injection

**Comment by kgabis** [comment]
Read the comment. It's just an example that shows how to use the API, it doesn't matter.

**Comment by oxr463** [comment]
Except for when people copy and paste it into their project...
