### ISSUE TITLE
Problems with numbers and serializing

### ISSUE THREAD

**Issue by akreft-cds** [kgabis/parson#127]
When I use `json_object_set_number` or `json_object_dotset_number` and then use `json_serialize_to_string`, the result is NULL. It has been working with `json_object_dotset_string` and `json_object_dotset_null` but now I cannot serialize numbers. The parsing seems to work.

```
JSON_Value* root_value = json_value_init_object();
JSON_Object* root_object = json_value_get_object(root_value);

json_object_set_number(root_object, "number", 625);

result = json_serialize_to_string(root_value);
```

**Comment by kgabis** [comment]
Please provide full example that I can compile to reproduce the bug (and make sure you're using the most recent version of parson).

**Comment by akreft-cds** [comment]
It looks like my problem is that the platform I am working on does not support sprintf float formatting or it is not yet enabled.

**Comment by kgabis** [comment]
Sorry but I can't guarantee support for non-standard libraries.
