### ISSUE TITLE
`json_serialize_to_buffer` should return serialized size

### ISSUE THREAD

**Issue by JayKickliter** [kgabis/parson#136]
The information is already available, and it makes sense to report it. `json_serialization_size()` appears to fail if the serialized size is greater than 1100, and it's a bit wasteful to serialize a thing only to know the size so you can serialize it again.

**Comment by kgabis** [comment]
It uses the same code as the serialisation so it's less likely to diverge and be incorrect. Are you sure you're using the most recent version? Because serialization buffer used to be 1100 bytes but it got changed in https://github.com/kgabis/parson/commit/921da6f5d7b82ac3c8c809341028daafe47e3210

**Comment by kgabis** [comment]
Closing this issue due to lack of response.
