### ISSUE TITLE
question: Does parson aim to be a streaming parser?

### ISSUE THREAD

**Issue by hansbogert** [kgabis/parson#138]
I can't find it explicitly, but does parson aim to be a streaming parser, i.e., does it have bounded memory usage? I might have to parse arrays of upfront unknown amount of items. Yet I'd really like the traversal capabilities of parson

**Comment by kgabis** [comment]
Sorry, streaming is not possible with parson. When it comes to memory usage you can use custom allocators with ```json_set_allocation_functions```.
