### ISSUE TITLE
Missing declaration for json_object_free?

### ISSUE THREAD

**Issue by whitsonk** [kgabis/parson#140]
If I use json_value_get_object should I not eventually call json_object_free to avoid a memory leak? If so, should the declaration be added to parson.h?

Compile time error...
error: 'json_object_free' was not declared in this scope.

Thanks.

**Comment by kgabis** [comment]
No, use json_value_free on root value.

**Comment by whitsonk** [comment]
Wow... That was fast! 

Thanks
