### ISSUE TITLE
Number parsing broken for some locales

### ISSUE THREAD

**Issue by yanchoyanev** [kgabis/parson#142]
Some locales use a comma as a decimal point. Others use the comma to separate thousands. In these cases the number parsing is broken if the value is not in double quotes, like this:

{
   Num: 9,
   Str: "something"
}

The strtod call should use the C locale, not the default one.

**Comment by kgabis** [comment]
Per https://github.com/kgabis/parson/issues/98#issuecomment-589346669. There's no good way of fixing this. Use setlocale.
