### ISSUE TITLE
How to maitain and reuse json objects and values?

### ISSUE THREAD

**Issue by liudr** [kgabis/parson#144]
Hi,

Thank you for writing the light-weight library! In my case, I'm using it on an iot device so memory is to be conserved and any leak will eventually crash it. So I want to know the proper way to reuse json objects and values, both for serialization and deserialization.

My understanding is for serialization illustrated in this snippet where I serialize a json body for https post data with a single name:value pair blobName:xxx:

```
	JSON_Value* root_valueS				= NULL;
	JSON_Object* root_objectS			= NULL;

	root_valueS = json_value_init_object();
	root_objectS = json_value_get_object(root_valueS);

	(void)json_object_set_string(root_objectS, "blobName", fileName);
	post_data = json_serialize_to_string(root_valueS);
...
	json_object_clear(root_objectS);
	json_value_free(root_valueS);
	free(post_data);



```
My understanding is the returned pointer from serialize is malloc'd so must be freed. Will the above root_valueS and root_objectS be reusable in a latter part of my code? Is the cleanup correct for this function to be called repeatedly for each time I do https post?

For deserialization, I am looking for a correlation id in the https response json body. I assume json_value_get_string returns a pointer to the value, not making a copy with malloc because the return value type is const?
```
	JSON_Value* root_valueDS			= NULL;
	JSON_Object* root_objectDS			= NULL;
	JSON_Value* correlationIdString_val	= NULL;
	root_valueDS = json_parse_string((const char *)receipt_upload_server_response_buffer);
	root_objectDS = json_value_get_object(root_valueDS);
	if (json_object_has_value(root_objectDS, correlationId_str))
	{
		correlationIdString_val = json_object_get_value(root_objectDS, correlationId_str);
		str_ptr=json_value_get_string(correlationIdString_val);
		strcpy((char*)correlationId,(const char*)str_ptr);
	}
	json_object_clear(root_objectDS);
	json_value_free(correlationIdString_val);
	json_value_free(root_valueDS);
```
Thanks for your help!

**Comment by kgabis** [comment]
You don't have to call ```json_object_clear```, calling ```json_value_free``` on the root value is enough. ```json_object_get_value``` and ```json_value_get_string ``` don't return a copy, so calling ```json_value_free(correlationIdString_val);``` is wrong. And to free a serialized string you have to use ```json_free_serialized_string```.

**Comment by liudr** [comment]
OK thank you for your quick response! Then what is the purpose of json_value_free(), only to free a json value initialized from json_parse_string() for deserialization and from json_value_init_object() for serialization?
If freeing the json values obtained from json_object_[dot]get_value() isn't necessary, then should I call delete or just abandon, i.e. use the same json value pointer in another assignment? I don't see a class in your code.

I read your source code and thought that json_free_serialized_string() just calls free() as a wrapper, right? I can do that to make it more clear.

**Comment by kgabis** [comment]
Yes, only root objects need to be freed, ```json_object_get_value``` only returns a pointer without doing a copy.
```json_free_serialized_string``` is ```free``` unless you use custom allocation functions.

You can look at source code in case of more questions, it should be fairly obvious how it works.
