### ISSUE TITLE
Integer get/set

### ISSUE THREAD

**Issue by sgh** [kgabis/parson#160]
It seems to me that integer get/set functions are missing. Why is only double available?

**Comment by kgabis** [comment]
Why not just do the cast from double to int yourself?

**Comment by sgh** [comment]
That is possible, but a double cannot consistently hold an int64 value. Most other api's have a distinction between floating points types and integer type of this exact reason.

I can do the implementation if you will accept the change after review.

**Comment by kgabis** [comment]
Please have a look at https://github.com/kgabis/parson/issues/134, I'm not planning to add big integer support.

**Comment by sgh** [comment]
regular int32 then ?

**Comment by kgabis** [comment]
But why? I can understand people making a case for int64, but int32 can easily fit within a double.

**Comment by sgh** [comment]
Casting from double<->int is as far as I know not 100% safe on all platforms. In any case it is safe if an actual integer type could be supported. As far as int64 goes - for my application - I use parson for both get and set, so compatabillity is not an issue for my isolated case.

**Comment by kgabis** [comment]
Sorry, I don't follow. Casts between floating point numbers and integers *are* deterministic. I'm not going to extend the api to avoid using ```(int)```. Besides, should I add functions for uint as well? What about char and short? uchar and ushort?

**Comment by kgabis** [comment]
I'm locking this conversation because it's leading nowhere.
