### ISSUE TITLE
undeclared identifier 'SIZE_MAX'

### ISSUE THREAD

**Issue by adamski** [kgabis/parson#167]
I am now getting this error building via clang on linux.

I assume it's since the 1.2.0 update since it did not occur previously.

**Comment by bluesky322** [comment]
yeah, I also got this error

**Comment by kgabis** [comment]
I'll submit a bugfix in a few minutes.

**Comment by kgabis** [comment]
It should compile now.

**Comment by adamski** [comment]
Thank you
