### ISSUE TITLE
Question on errors - Get information about what failed

### ISSUE THREAD

**Issue by priesf** [kgabis/parson#182]
Hello, 
is there any possibility to get more information on the error when a parson function returns "JSONFailure"? 
Currently I have to debug to the failing function to find out what is going on. 

Am I missing any function call to determine any further information? 
Any plans on extending the (really useful) library with this kind of information / functions?

**Comment by kgabis** [comment]
I don't think this can be easily added to parson at this point without a major rewrite, sorry :(
