### ISSUE TITLE
json_serialize_to_string: unnecessary escaping of "/"

### ISSUE THREAD

**Issue by stephenmathieson** [kgabis/parson#20]
`json_serialize_to_string()` escapes `"/"`, though it doesn't need to:

``` c
int main(void) {
  JSON_Value *object = NULL;
  JSON_Status ret;
  char *json = NULL;

  object = json_value_init_object();
  ret = json_object_set_string(json_object(object), "foo/bar", "1.2.3");
  if (JSONSuccess != ret) {
    fprintf(stderr, "OH NO!!\n");
    json_value_free(object);
    return 1;
  }

  json = json_serialize_to_string(object);
  printf("%s\n", json);
  free(json);
  json_value_free(object);

  return 0;
}
```

yields:

``` sh
./example
{"foo\/bar":"1.2.3"}
```

though `{"foo/bar":"1.2.3"}` is perfectly valid.

**Comment by kgabis** [comment]
/ are being escaped again (https://github.com/kgabis/parson/commit/8324ff92bf91c644458524b3b5fb45f2d2d2d7ba) to allow serialized json to be embeddable in xml/html.

**Comment by stephenmathieson** [comment]
@kgabis can we set an option to turn this off?  see https://github.com/clibs/clib/pull/124#issuecomment-158469433

**Comment by kgabis** [comment]
I understand it doesn't look as pretty as it used to, but I'd rather not grow the API just for that.
