### ISSUE TITLE
sprintf hard-deprecated on MacOS prevents compiling

### ISSUE THREAD

**Issue by rplsix** [kgabis/parson#207]
Error given if compiling on MacOS:
```
parson/parson.c:1247:27: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
                written = sprintf(num_buf, parson_float_format, num);
                          ^
```

Affected are these lines starting at 1247:
```
                written = sprintf(num_buf, parson_float_format, num);
            } else {
                written = sprintf(num_buf, PARSON_DEFAULT_FLOAT_FORMAT, num);
```

If changed to this it would be compiling:
```
                written = snprintf(num_buf, sizeof(num_buf), parson_float_format, num);
            } else {
                written = snprintf(num_buf, sizeof(num_buf), PARSON_DEFAULT_FLOAT_FORMAT, num);
```

**Comment by kgabis** [comment]
Hi, it's not that simple since there's no snprintf in C89. You can use ```-Wno-deprecated-declarations```.
Also, ```sizeof(num_buf)``` is wrong.

**Comment by rilysh** [comment]
macOS by default uses clang, so using pragmas can be a workaround
```c
#ifdef __APPLE__
#ifdef __clang__
    #pragma clang diagnostic push
    #pragma clang diagnostic ignored "-Wdeprecated-declarations"
    /* sprintf(...) function */
    #pragma clang diagnostic pop
#endif
#endif
```

There's another thing can be done is to create another function that behaves like a `snprintf(...)`; a custom variadic function using `vsnprintf(...)`. Though it's not a part of C89 [spec](http://port70.net/%7Ensz/c/c89/c89-draft.html).

**Comment by kgabis** [comment]
Fixed in https://github.com/kgabis/parson/commit/ba29f4eda9ea7703a9f6a9cf2b0532a2605723c3
