### ISSUE TITLE
Validate JSON inputs

### ISSUE THREAD

**Issue by bendrissou** [kgabis/parson#208]
Hello,

I am looking for a way to validate JSON inputs when parsing.

I know that there is function `json_validate`. However, you need to provide a schema.

Is there a way to validate JSON inputs? And reject inputs that are not valid JSON?

**Comment by bendrissou** [comment]
The current parser consumes the valid JSON prefix and ignores any remaining invalid sequences.

For example:

`{"var":null}}}}}`

When given the above input, the parser doesn't return any error,

**Comment by bendrissou** [comment]
Hi @kgabis 

Is there any flag or function that enables input validation?

**Comment by kgabis** [comment]
Hi, there's not function in the API that will test if a string is a JSON compliant text.
