### ISSUE TITLE
Unstable memory access conflicts that occur when running on Win7

### ISSUE THREAD

**Issue by Edda1024** [kgabis/parson#209]
Hi,
We tried to use the library to read and manipulate json files (in the previous operation, we set the heap reserve size of the program to 5120000 for stability), this code runs relatively stable on Win10, and when we move the test environment to the Win7 system of the virtual machine, there are more frequent memory access conflicts, this error occurs once every three times on average, we wonder if it is due to some usage specification that we ignored or other reasons?

`CFile tempFile;
			tempFile.Open(filePathtemp,CFile::modeCreate | CFile::modeWrite);
			tempFile.Close();

			JSON_Value* root_value = NULL;

				root_value = json_value_init_object();

				JSON_Object* root_object = json_value_get_object(root_value);
				//*********************
				JSON_Value* dataValueArray = json_value_init_array();

				JSON_Array* dataObjectArray = json_value_get_array(dataValueArray);

				for (int i = 0; i < m_vecJson.size(); i++)
				{
					JSON_Value* pValue = json_value_init_object();

					if (pValue == NULL)
					{
						break;
					}

					JSON_Object* pObject = json_value_get_object(pValue);

					if (pObject == NULL)
					{
						break;
					}

					std::string str1 = CT2A(m_vecJson.at(i)->fileName.GetString());
					std::string str2 = CT2A(m_vecJson.at(i)->version.GetString());
					std::string str3 = CT2A(m_vecJson.at(i)->url.GetString());
					std::string strNum = to_string(m_vecJson.at(i)->versionNum);
					const char* ch1 = str1.data();
					const char* ch2 = str2.data();
					const char* ch3 = str3.data();

					json_object_set_string(pObject, string("fileName").data(), ch1);
					json_object_set_string(pObject, string("versionNum").data(), strNum.data());
					json_object_set_string(pObject, string("version").data(), ch2);
					json_object_set_string(pObject, string("type").data(), string("2").data());
					json_object_set_string(pObject, string("url").data(), ch3);

					json_array_append_value(dataObjectArray, pValue);
				}
				//******************

				json_object_set_number(root_object, string("code").data(), 0.0);
				json_object_set_string(root_object, string("msg").data(), string("onlymessage").data());

				json_object_set_value(root_object, string("data").data(), dataValueArray);

				const char* FILE_NAME = str.c_str();
				JSON_Status status = json_serialize_to_file(root_value, FILE_NAME);

			if (root_value != NULL) {
				
				json_value_free(root_value);                  //The error points to this function
				root_value = NULL;
			}`
![image](https://github.com/kgabis/parson/assets/114471555/da70a1ad-d350-48b4-af98-a0e440e4e320)
![image](https://github.com/kgabis/parson/assets/114471555/b7b62387-0b9d-4dc9-8c51-23ea1a747827)

**Comment by kgabis** [comment]
I'm not able to reproduce this, could you provide a self-contained piece of code (no external files required) that show this bug?

**Comment by Edda1024** [comment]
> I'm not able to reproduce this, could you provide a self-contained piece of code (no external files required) that show this bug?

After troubleshooting, it was found that memory leaks in other code caused the problem, and the problem has been resolved
