### ISSUE TITLE
NULL string values when escaped backslashes are present

### ISSUE THREAD

**Issue by NialG** [kgabis/parson#26]
This seems related to the fixes put in place for issue #24, but I'm now seeing `NULL` values returned for any string which contains an escaped backslash.

Given the following code I'd expect `name` to contain the value `John\ Smith`. Instead, it's returned as `NULL`.
```
JSON_Value *v = json_parse_string("{\"name\":\"John\\ Smith\"}");
JSON_Object *o = json_value_get_object(v);

const char *name = json_object_get_string(o, "name");
printf("name: %s\n", name);
```

**Comment by kgabis** [comment]
Hi, this is expected. 
I've fixed the issue with parsing strings when using string setting functions, however it does not apply to this case. ```"{\"name\":\"John\\ Smith\"}"``` will become ```{"name":"John\ Smith"}``` before being passed to ```json_parse_string``` and, since it's not a valid json string, NULL will be returned.
