### ISSUE TITLE
valgrind complain on strlen

### ISSUE THREAD

**Issue by lmcmgig** [kgabis/parson#28]
Since the pointer of the output is known and you control the end pointer, why not do a simple subtraction.  It will be even faster than scanning the string for \0 with strlen.

Here the 1 line fix.

```
--- parson/parson.c
+++ parson/parson.c
@@ -435,11 +435,11 @@
         }
         output_ptr++;
         input_ptr++;
     }
     *output_ptr = '\0';
-    if (try_realloc((void**)&output, strlen(output) + 1) == JSONFailure)
+    if (try_realloc((void**)&output, (output_ptr-output) + 1) == JSONFailure)
         goto error;
     return output;
 error:
     free(output);
     return NULL;
```

**Comment by kgabis** [comment]
Thanks, I changed it in https://github.com/kgabis/parson/commit/2b4d17b3376488f17d3e9ba9822d85a2fd55f8a1.

**Comment by lmcmgig** [comment]
Great, thanks.

Mathieu Giguere
