### ISSUE TITLE
Wrapping objects/arrays/etc. into values

### ISSUE THREAD

**Issue by jleeothon** [kgabis/parson#30]
How can we wrap a `JSON_Object *`, `JSON_Array *`, `const char*`, or `double` around a `JSON_Value`? Or is there such a feature that I've missed?

This could also be useful if e.g. you have a `JSON_Object` but you want to use `json_value_deep_copy` or `json_serialize_to_string`—both receive `JSON_Value *` arguments. Situations where you have an object but not a value include when it has been passed as a function argument.

Then we could do something like:

```C
void a(const char *s) {
    JSON_Value *v = json_parse_string(s);
    JSON_Object *o = json_value_get_object(v);
    // do lots of processing with o
    b(o);
    json_value_free(v);
}

void b(JSON_Object *o) {
    // do lots of processing with o
    printSomewhere(json_serialize_to_string(json_object_to_value(o)));
}
```

**Comment by kgabis** [comment]
Currently there are no functions to wrap objects and arrays with JSON_Value (however you can create values from strings and doubles using json_value_init_string/double). So if you need to serialize an object you have to pass it as JSON_Value. I realize this is not perfect.

**Comment by kgabis** [comment]
You should be able to do this now using json_object_get_wrapping_value(...) and json_array_get_wrapping_value(...) (and then calling json_value_deep_copy(...)). A bit late, but still :)

**Comment by jleeothon** [comment]
Ah, still, thanks! I'll consider updating the project where I consume `parson`. :) Happy holidays.
