### ISSUE TITLE
dotset*() to understand printf-style names?

### ISSUE THREAD

**Issue by ThomasAdam** [kgabis/parson#31]
Hi,

I've found in trying to programatically generate a JSON structure that I'm having to make a lot of snprintf() calls to form the key name for a dotset*() operation when iterating over various pieces of data.

I was wondering if parson would benefit from understanding a printf-style string, and to interpolate that appropriately?  I'm happy to do the work on the basis that it might be accepted.

**Comment by kgabis** [comment]
Hi,
I think this is very specific to your use case and I don't think this should end up in parson's API. You should probably wrap it in a function accepting format string and varargs if you keep calling snprintf.
