### ISSUE TITLE
return value from json_object_dotget_number

### ISSUE THREAD

**Issue by mrkozmic** [kgabis/parson#32]
Hi,
I have been using parson for a while and I love it!
However, I have a problem with the json_object_dotget_number() function.
json_object_dotget_number() returns '0' on fail as shown below so there is no way to distinguish between an error and value '0'. 

double        json_object_dotget_number (const JSON_Object *object, const char *name); /* returns 0 on fail */

I suggest returning the value as a function argument and use the return value for error only.
I also suggest using 0 for success and -1 for failure.

 int json_object_dotget_number (const JSON_Object *object, const char *name, double *number); 
/* returns 0 on success, -1 on fail */

**Comment by kgabis** [comment]
Hi, I'm glad you like parson :)
I agree that this is not perfect but I won't be able to change the API now. I suggest using json_type(json_object_get_value(object, name)) == JSON_Number or json_validate. I should add json_object/array_get_type function though...
