### ISSUE TITLE
parson does not compile with c++ compiler

### ISSUE THREAD

**Issue by wiguy** [kgabis/parson#33]
Changed compiler from gcc to g++ in Makefile.
Get error
parson.c: In function ‘JSON_Status json_array_resize(JSON_Array*, size_t)’:
parson.c:407:65: error: invalid conversion from ‘void*’ to ‘JSON_Value** {aka json_value_t**}’ [-fpermissive]
     new_items = parson_malloc(new_capacity * sizeof(JSON_Value*));

It seems to be as easy as adding a simple cast, changing line 407 to
new_items = (JSON_Value**)parson_malloc(new_capacity * sizeof(JSON_Value*));

**Comment by kgabis** [comment]
Fixed in https://github.com/kgabis/parson/commit/849f00728b338aac6694728603b463667e79c81d, thanks for reporting this bug.
