### ISSUE TITLE
Escaping "/"

### ISSUE THREAD

**Issue by fulvioesposito** [kgabis/parson#34]
Just a suggestion, but many json parsers escape "/" because in script tags "</" is not allowed, so there's a slight chance having some json in a script tag can lead to invalid html. I think it's just a matter of adding a case in json_serialize_string:

case '/': APPEND_STRING("\\\\/"); break;

**Comment by kgabis** [comment]
This was already addressed in issue https://github.com/kgabis/parson/issues/20. I don't see a good reason to escape "/" so I'm gonna leave it as it is :)

**Comment by espositofulvio** [comment]
Though it's not necessary, if you embed json in a web page you'll hit a problem if the json includes some sort of html in it:

    <script>
    var json = '{ "myhtml": "<h>some text</h>" }';
    </script>

In this case the html is invalid because of the "</h>" in the json. That's why many parsers escape "/".

**Comment by kgabis** [comment]
/ should now be escaped when serializing (https://github.com/kgabis/parson/commit/8324ff92bf91c644458524b3b5fb45f2d2d2d7ba). It's sad that this is not defined by the json standard, however accepting escaped / seems to exist only because of xml/html embeddability.
