### ISSUE TITLE
null parsing

### ISSUE THREAD

**Issue by anporumb** [kgabis/parson#39]
Hello kgabis,

As per json.org, null is a valid JSON value.

I would expect the following code to print "parsing null success!". Instead it prints "cannot json_parse_string null".

```c
#include <stdio.h>

#include "parson.h"

int main(int argc, char** argv)
{

	JSON_Value* v = json_parse_string("null");
	if (v == NULL)
	{
		printf("cannot json_parse_string null\n");
	}
	else
	{
		printf("parsing null is success!\n");
		json_value_free(v);
	}

    return 0;
}
```
Thank you.

Best Regards,
Andrei Porumb

**Comment by kgabis** [comment]
Hello Andrei,
From [RFC 4627](https://www.ietf.org/rfc/rfc4627.txt): “A JSON text is a serialized object or array.”. However, this limitation seems to have been lifted in [RFC 7159](https://tools.ietf.org/html/rfc7159) so I don't think there's a reason to keep it in parson.

Regards,
Krzysztof

**Comment by kgabis** [comment]
Fixed in https://github.com/kgabis/parson/commit/f860d3dd1b52b6cec3e69b9212641414a4ede9d1.

**Comment by anporumb** [comment]
Much appreciated!
