### ISSUE TITLE
Microsoft's _CRT_SECURE_NO_WARNINGS

### ISSUE THREAD

**Issue by anporumb** [kgabis/parson#40]
Hello kgabis,

I would like to propose the following (small) improvement:

```c
#ifdef _MSC_VER
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif /*_CRT_SECURE_NO_WARNINGS*/
#endif
```
Thank you.

Best Regards,
Andrei Porumb
PS: this helps in the cases where the build system blindly defines _CRT_SECURE_NO_WARNINGS for all files.

**Comment by kgabis** [comment]
Hi Andrei,
I fixed this in https://github.com/kgabis/parson/commit/77ef99571e94ae69bfd050e8327b08635c237751.

Regards,
Krzysztof
