### ISSUE TITLE
missing object key existance function

### ISSUE THREAD

**Issue by alexandercerutti** [kgabis/parson#42]
Hi there,
I noticed that is missing a function such **int json_object_string_exists(** _JSON_Object *object_, _const char *name_ **)** that checks (and return like an int) if a key (or string) in a Object exists. If I use json_object_get_string over an unexisting string, program gives Segmentation Fault (code dump).
Could you add it? Thank you.

**Comment by kgabis** [comment]
Hi,
You should check if json_object_get_string has returned NULL before using the result (same goes for json_object_get_object and json_object_get_array). However, it doesn't work with numbers and booleans (you must use json_object_get_value first and check type). I might consider adding some options to check if a field with a certain type exists in the future.

**Comment by alexandercerutti** [comment]
Oh, okay, perfect! Thank you!
