### ISSUE TITLE
Mix of tabs and spaces leads to warning about indentation

### ISSUE THREAD

**Issue by lindig** [kgabis/parson#47]
Around parson.c:276 tabs are used for indentation rather than spaces like everywhere else. This leads to a compiler warning. The warning is unfounded, IMHO.

 
		gcc -std=gnu99 -g -fpic -Wall -c -o parson/parson.o parson/parson.c
		parson/parson.c: In function ‘remove_comments’:
		parson/parson.c:282:13: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
								 for (i = 0; i < (ptr - string) + end_token_len; i++)
								 ^~~
		parson/parson.c:284:12: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
								string = ptr + end_token_len - 1;
								^~~~~~

**Comment by kgabis** [comment]
Thanks, I've fixed this in https://github.com/kgabis/parson/commit/c22be794ce4d1befbb8c68487a96a6aa8d482e90.
