### ISSUE TITLE
Code-quality scan (Version d7726760e0532eaa65e439c3f9403312d819be52)

### ISSUE THREAD

**Issue by AlexShkunov** [kgabis/parson#60]
Currently used version of the library (Clone-Version 08.02.2016)
We have couple of findings from Code-quality tool:

File                 ID       Severity      Method                         Message
parson.c             142      Critical      json_serialize_to_buffer_r     Pointer 'key' returned from call to function 'json_object_get_name' at line 768 may be NULL and may be dereferenced at line 771.
parson.c             148      Critical      json_value_equals              Pointer 'a_string' returned from call to function 'json_value_get_string' at line 1722 may be NULL and will be dereferenced at line 1724.
parson.c             150      Critical      json_serialize_to_buffer_r     Pointer 'string' returned from call to function 'json_value_get_string' at line 797 may be NULL and will be dereferenced at line 798.
parson.c             152      Critical      json_value_equals              Pointer 'b_string' returned from call to function 'json_value_get_string' at line 1723 may be NULL and will be dereferenced at line 1724.
parson.c             155      Critical      json_value_deep_copy           Pointer 'temp_string' returned from call to function 'json_value_get_string' at line 1197 may be NULL and will be dereferenced at line 1198.

**Comment by kgabis** [comment]
They all look like false positives but I'll consider adding additional checks.
