### ISSUE TITLE
Number max size in serialization 

### ISSUE THREAD

**Issue by koper89** [kgabis/parson#61]
Just a question about max size in json_serialization_size and json_serialization_size_pretty functions, there's 1100 character long buffer for pre-parsing numbers, where's this number coming from? Wouldn't it be better to use parson_malloc + parson_free if there's need for such a long buffer for just a number, or is it misclicked 100? More than 1000 characters seems like an overkill?

**Comment by kgabis** [comment]
It's because http://stackoverflow.com/a/1701272
Besides, it doesn't matter, 1100 bytes is not that much.
