### ISSUE TITLE
Support file encodings other than ANSI

### ISSUE THREAD

**Issue by andrew-buckley** [kgabis/parson#65]
Currently parson opens files using a call to `FILE *fp = fopen(filename, "r");`. This will assume the file is encoded as ANSI which is not always the case. `fopen` can take an optional `ccs=<encoding>` argument, and values of `<encoding>` can be "UNICODE", "UTF-8", and "UTF-16LE". Please consider changing the call to `fopen` passing the `ccs=UNICODE` argument. 

I played around with this and ended up changing a lot of parson internals such as allowing the switch between wchar_t* and char*, and modifying the file open calls to `FILE *fp = fopen(filename, "r, ccs=UNICODE");` however there ended up being quite a bit of changes and more that I would have needed to do to make it complete, there was a simpler way to go about it which as just changing the functions which open files to read into a wchar_t* and then put that into a char*. I decided to table my work as it was starting to get extensive, and instead suggest the change here just in case you are already working on this or don't plan on supporting unicode.

**Comment by kgabis** [comment]
I'd rather not add "ccs=UNICODE" to fopen calls because it's non-standard. I guess the only thing I should do to make UTF-8 BOM work is to ignore "EF BB BF" bytes at the start of a file/buffer. Is that right?
