### ISSUE TITLE
Removing dependency on sscanf

### ISSUE THREAD

**Issue by compulim** [kgabis/parson#68]
I am suggesting to remove dependency on `sscanf`. It was only used twice for parsing hex numbers `"%4x"` and could be easily replaced.

Primarily, it is because of [this issue](https://github.com/Azure/azure-iot-sdk-c/issues/52) in [Azure IoT SDK for C](https://github.com/Azure/azure-iot-sdk-c). The SDK relies on [parson](https://github.com/kgabis/parson). But since some Arduino devices did not implement `sscanf`, thus, they cannot use Azure IoT SDK.

As I dig further, I found that parson only used `sscanf` twice for parsing UTF-16 in hex. So I am suggesting if it could be replaced. Apart from Azure IoT SDK, the change could also benefit other Arduino users by using parson for their project.

I have forked parson and replaced `sscanf` with this [commit](https://github.com/compulim/parson/commit/7920413af9599f376db500285441b2f5ccdafd39).

Thanks!

**Comment by kgabis** [comment]
I did think about removing this dependency some time ago so it's nice to see someone else do it :) Could you add forward declarations for scan_utf_16 and scan_hex (to make it consistent with the rest of code) and create a merge request?

**Comment by compulim** [comment]
Pull request #69 created. Closing this issue and continue to track in PR.

**Comment by kgabis** [comment]
Fixed in https://github.com/kgabis/parson/commit/96150ba1fd7f3398aa6a4dead0a63d9d9ac1c189, but I can't guarantee that I won't use sscanf in the future. It's a standard function and it's impossible to support every non-standard library, however I will try to avoid it if I can.
