### ISSUE TITLE
Add support for per-node floating point format (for numbers)

### ISSUE THREAD

**Issue by jamesbond3142** [kgabis/parson#71]
I have the patch here: https://gist.github.com/jamesbond3142/19a857d2cc31e2fd550f8fd129d5802f
It's quick and dirty and the format is supposed to be constant (not malloc-ed or snprintf etc) as no memory management is done for that.
Backward compatible (I created new function name).

**Comment by kgabis** [comment]
Well, I don't understand a rationale behind this feature. Care to explain?

Also, please read "Contributing" in readme.

**Comment by jamesbond3142** [comment]
Many reasons, for me at least. Number object can be anything, including integer larger than "int". In this case, we want to serialise it as integer with no decimals "%.0f". 

Also, certain number objects have certain precisions, and we want them to be output as such, instead of the generic six digits decimal. Some may have only one decimal, some twelve.

Consider this use case: You have an object that contains GPS coordinate (latitude, longitude) and a Unix-epoch millisecond timestamp. The coordinates needs at least 8 digits to serialise correctly. The timestamp is bigger than an "int", but you don't want to serialise it with any decimal digits. How would you do it in the existing version? 

The patch makes it possible to attach a floating-format to each node; so they are correctly serialised according to their (preset) precision. If you don't attach anything (use the original APIs), the "number_format" is NULL and the default DOUBLE_SERIALIZATION_FORMAT is used, as before.

Hope this clarifies.

**Comment by mbelicki** [comment]
The most obvious way to go around this issue is to store numbers as strings. And to be honest I think it's the only way to have any guarantee about precision when transferring numbers as JSON. 

Adding additional pointer to each node increases size of the parsed tree (by at least 25%), which with current API you have to always hold in the memory at once. That might not be a welcome change for some of the users.

**Comment by jamesbond3142** [comment]
Yes, that's the most obvious way and I tried that. But:
a) it's mightily inconvenient
b) you need to convert that back to number on the other end, too (when you parse the data back).
For (a) you can create wrapper functions but (b) is not so easy because the other end isn't necessarily using parson (e.g. in my case the other end is parsed by gson, passing a String when it expects long will generate exception).

I agree that the of cost of additional 25% memory is problematic if you need to have a very large tree. 

Another way I'd do it is to pass a callback down the path of json_serialize_* function calls. The callback will get item name, and it should return format; in absence of callback (or if it returns NULL) just proceed with default format. I actually went down this path before but found the change very intrusive (to existing API) and it also caused me to handle more logic on the callback than I'd like. It's always trade-off.

All being said, parson is a very nice little library with enough feature to make it useful and little enough bloat to make it manageable and understandable. Thank you for releasing parson.

**Comment by kgabis** [comment]
I don't think that having field specific precision is the right answer. Ideally you would be able to specify desired precision when calling json_serialize, but that would require adding another set of functions.
Maybe current number of decimal places used for serialization is too small, I'll consider increasing it and using %g format specifier. I'll keep this open for now.

**Comment by jamesbond3142** [comment]
> Maybe current number of decimal places used for serialization is too small, I'll consider increasing it and using %g format specifier.

Any number of decimal places may be too small or too big depending on the needs. If you think that per-node specification is too heavy (or too complicated) for now, then perhaps you can provide a function for global specification (instead of hardcoding to DOUBLE_SERIALIZATION_FORMAT), something like you do with parson_malloc. It does not help me this way but may help others.

**Comment by mbelicki** [comment]
> Any number of decimal places may be too small

Well with `"%.*g"` and `DBL_MANT_DIG` it will never be too small. As for too large numbers users can always round their values to lose precision. It's quite clunky but allows to control serialization precision.

**Comment by moe123** [comment]
Hello gents, related to this topic : double parsing locale independent: (I have a patch for this real-floating-point issue ; as well as handling sint64 too, if any interested in let me know)

`#	if defined(_MSC_VER)
#		include <stdlib.h>
#		include <locale.h>
		typedef _locale_t parson_locale_t
#	else
#		include <stdlib.h>
#		include <xlocale.h>
		typedef locale_t parson_locale_t
#	endif

static int g_parson_locale_init = 0;
static parson_locale_t g_parson_locale;

parson_locale_t parson_locale()
{
	if (!g_parson_locale_init) {
		g_parson_locale_init = 1;
#	if defined(_MSC_VER)
		g_parson_locale = _create_locale(LC_ALL, "C");
#	else
		g_parson_locale = newlocale(LC_ALL_MASK, NULL, NULL);
#	endif
	}
	return g_parson_locale;
}

double parson_strtod(const char * nptr, char ** endptr)
{
#	if defined(_MSC_VER)
	return _strtod_l(nptr, endptr, parson_locale());
#	else
	return strtod_l(nptr, endptr, parson_locale());
#	else
}`

**Comment by kgabis** [comment]
Unfortunately this solution is not portable so I cannot add it to parson. I'm open to other suggestions though...

**Comment by kgabis** [comment]
Low precision problem should be fixed in https://github.com/kgabis/parson/commit/4e8a9012423dd8dda6b8f7b4cae40cbd440011a8
