### ISSUE TITLE
Move Type definitions from parson.c to parson.h

### ISSUE THREAD

**Issue by robopt** [kgabis/parson#73]
When debugging applications, without access to the type definitions, attempting to access JSON Object names or values causes an "dereferencing pointer to incomplete type" compiler error.

names:
`ubp.c: In function ‘json_to_response_two’:
ubp.c:59:41: error: dereferencing pointer to incomplete type
    printf("name: %s, value: %s\n",object->names[j], json_value_get_string(object->values[j]));`
and for values:
`ubp.c:59:58: error: dereferencing pointer to incomplete type
    printf("name: %s, value: %s\n",object->names[j], json_value_get_string(object->values[j]));`

Moving these to the header file resolves this issue, and allows for better debugging.

**Comment by kgabis** [comment]
Please use ```json_object_get_name``` and ```json_object_get_value_at```. Types are hidden intentionally, otherwise it would be impossible for me to make any changes to them without braking client code.
