### ISSUE TITLE
Needs well defined behavior surrounding memory allocation/ownership

### ISSUE THREAD

**Issue by zafields** [kgabis/parson#74]
Documentation is not crisp about when I need to free resources versus when the library will free resources on my behalf.

There are comments in the header file in some places that indicate how memory should be handled...

> ```
> /* Works like dotget functions, but creates whole hierarchy if necessary.`
> * json_object_dotset_value does not copy passed value so it shouldn't be freed afterwards. */ 
> ```

However, the header offers no advice for the management of the string returned by `const char  * json_object_get_string (const JSON_Object *object, const char *name);`

The README ("Persistence" section) shows, `json_object_get_string` being used without a call to free, but this is uncommon behavior for c libraries and it would be nice if it were well defined.

**Comment by kgabis** [comment]
This function returns a const pointer so you're not supposed to manage it at all (and I'm pretty sure that other libraries don't expect you to free a const pointer). You're only supposed to free strings returned by json_serialize_to_string (+pretty) using quite descriptive json_free_serialized_string.
