### ISSUE TITLE
Parson fails to parse a large JSON file

### ISSUE THREAD

**Issue by procedural** [kgabis/parson#75]
Test on this json file (>70k loc, 2.6 MB): https://gist.githubusercontent.com/procedural/91a5273d7e6d354885def118bae5acea/raw/26d9ff4ed9aa3a88e2845a64f42eac74528bdb6f/TestParson.json

Repro code:
```C
#include "parson.h"
#include <assert.h>

int main() {
  JSON_Value * root_value = json_parse_file("TestParson.json");
  assert(json_value_get_type(root_value) == JSONArray);
  json_value_free(root_value);
}
```
Assert is triggered despite that JSON file is correct, just a little bit big :)

**Comment by kgabis** [comment]
It fails because nesting is too deep. Current limit is 20 and it's based on a test file from json.org but I think it's too low and should be increased. 2048 levels of nesting ought to be enough for anybody.

**Comment by kgabis** [comment]
Should be fixed now.

**Comment by procedural** [comment]
@kgabis Thanks!
