### ISSUE TITLE
memory allocation

### ISSUE THREAD

**Issue by Ron89** [kgabis/parson#83]
In the implementation, I see multiple instances where `NULL` is used to check the sanity of the array. If pointer pointing to `NULL` while a pointer to an `JSON_Value` is expected, the function returns `JSONFailure`. This design is OK if allocated space is properly zerorized. However, in current implementation, `json_malloc` is a simple wrapper over the system `malloc`, and does not provide all zero memory block. I recommend us change the implementation into a standard malloc followed by a memset.

On the other hand, in memory extension, is there any specific reason why `malloc` and manual copy over is preferred over `realloc`?

**Comment by kgabis** [comment]
I'm sorry, could you explain more clearly why non-zeroed memory can cause bugs and link to a specific place in the source code?
malloc and free are wrapped with parson_malloc and parson_free because they can be overwritten by users with json_set_allocation_functions. I'm not using realloc because I would have to write my own implementation (which is trivial), but I didn't bother because it would only be used in few places.

**Comment by Ron89** [comment]
Sorry, my mistake. The place I actually saw was in parson.c:1559 `temp_value==NULL`. I mistakenly though object were given a same treatment. Turned out it wasn't.

If all operation is performed with exposed API, non-zeroed malloc under this design will not cause issue. However, if user chose to manually resort array or object's order, or nullify/add some entry. There is a chance that the count is not properly adjusted. Checking if object operated on is NULL could provide more immediate feedback for the programmer during debugging. Or is this not part of the consideration, since parson.c:1559 seems to be the odd-out one?

**Comment by kgabis** [comment]
I assume that all operations will be performed using the api, otherwise it's impossible to guarantee anything. Direct access to items is not exposed so if a user decides to access and manipulate them on his own then it's not my responsibility to support it.
