### ISSUE TITLE
Add licensing file to source

### ISSUE THREAD

**Issue by jdswensen** [kgabis/parson#87]
It looks like you licensed this project under the MIT License ([bottom of page](http://kgabis.github.io/parson/)), but it isn't very obvious. Including a license in the source would clarify that.

**Comment by kgabis** [comment]
Isn't it enough that every source file has the mit license on the very top, or am I missing something?

**Comment by chedr** [comment]
Adding a LICENSE file is usually a standard practice and would integrate better with Github. An icon would be added in the commit/release/contributions bar. As you've mentioned I discovered the license by reading the top of the header file. :)

**Comment by kgabis** [comment]
I've added a LICENSE file.
