### ISSUE TITLE
High stack usage

### ISSUE THREAD

**Issue by thomafred** [kgabis/parson#88]
The parson serialization functions use considerable stack-space:

```gdb
parson/parson.c: In function 'json_serialization_size':
parson/parson.c:1420:8: warning: stack usage is 1168 bytes [-Wstack-usage=]
 size_t json_serialization_size(const JSON_Value *value) {
        ^~~~~~~~~~~~~~~~~~~~~~~
parson/parson.c: In function 'json_serialization_size_pretty':
parson/parson.c:1480:8: warning: stack usage is 1112 bytes [-Wstack-usage=]
 size_t json_serialization_size_pretty(const JSON_Value *value) {
```
This is not very friendly to low-resource environments such as embedded controllers. As an example, the Arduino has only 2kB of SRAM.

**Comment by kgabis** [comment]
This was already mentioned in https://github.com/kgabis/parson/issues/61.
Offending buffer is defined here https://github.com/kgabis/parson/blob/e112626cb5223670b7791c7482f3767c09e2752f/parson.c#L1419 and used here https://github.com/kgabis/parson/blob/e112626cb5223670b7791c7482f3767c09e2752f/parson.c#L924

I don't see a better way to accomplish this since I cannot use snprint, but I'm open to suggestions.

**Comment by thomafred** [comment]
Due to some stack-related issue, I recently moved the stack-allocated `char num_buf[1100]` out to a static variable. Of course, this is not a good solution, and only serves as a quick fix.

You may want to take user-considerations into account. For example allow the user to select between single or double precision. You could also take digit precision into account, as it is not necessary to print 1023 digits of a single-precision number.

I also think that you can allow different user-scenarios. For small embedded controllers, you may not want to use floating point numbers at all, in which case disabling the encoding of them may be advantageous. Other micro-controllers have an FPU which supports single-precision math. In this case it is not necessary to support double-precising encoding as it will never be used.

For my use case, I would not need floating-point numbers at all. This having a macro switch to disable this would be nice:

```c
#ifndef PARSON_DISABLE_FLOATING_POINT
#define PARSON_NUMBUF_SIZE    (1100)
#else
#define PARSON_NUMBUF_SIZE    (256)  /* From thin air */
#endif /* !defined(PARSON_DISABLE_FLOATING_POINT) */
```

Better yet, maybe set `PARSON_NUMBUF_SIZE` based on stdlib-values ([referenced](https://stackoverflow.com/questions/1701055/what-is-the-maximum-length-in-chars-needed-to-represent-any-double-value/1701272#1701272) from #63)

```c
#ifndef PARSON_DISABLE_FLOATING_POINT
#include <float.h>
#define PARSON_NUMBUF_SIZE    (3 + DBL_MANT_DIG - DBL_MIN_EXP)
#else
#define PARSON_NUMBUF_SIZE    (256)  /* From thin air */
#endif /* !defined(PARSON_DISABLE_FLOATING_POINT) */
```

Of course, I am aware that this will disable floating-point decoding as well as encoding. This should probably be handled by a cast in order to maintain encoding/decoding symmetry. This could also be handled by the macro-switch above:

```c
#ifndef PARSON_DISABLE_FLOATING_POINT
#include <float.h>
#define PARSON_NUMBUF_SIZE    (3 + DBL_MANT_DIG - DBL_MIN_EXP)
typedef double jsonNumber;
#else
#define PARSON_NUMBUF_SIZE    (256)  /* From thin air */
typedef long jsonNumber;
#endif /* !defined(PARSON_DISABLE_FLOATING_POINT) */

/* ... */

jsonNumber json_object_get_number(const JSON_Object *object, const char *name);

/* ... */

JSON_Status json_object_set_number(JSON_Object *object, const char *name, jsonNumber number);

/* ... */
```

Lastly, in order to save the user lots of compiler-flags, we may use a configuration-header:

```c
#ifdef PARSON_USER_CONFIG
#include "parson_config.h"
#endif

#ifndef PARSON_DISABLE_FLOATING_POINT
#include <float.h>
#define PARSON_NUMBUF_SIZE    (3 + DBL_MANT_DIG - DBL_MIN_EXP)
typedef double jsonNumber;
#else
#define PARSON_NUMBUF_SIZE    (256)  /* From thin air */
typedef long jsonNumber;
#endif /* !defined(PARSON_DISABLE_FLOATING_POINT) */

/* ... */

jsonNumber json_object_get_number(const JSON_Object *object, const char *name);

/* ... */

JSON_Status json_object_set_number(JSON_Object *object, const char *name, jsonNumber number);

/* ... */
```

Compiling changing the configuration should then be easy when setting compiler-flag `-DPARSON_USER_CONFIG`

**Comment by kgabis** [comment]
Since I'm using scientific notation for large/small numbers since switching float print format from %f to %1.17g there's no need to allocate so large buffer. Right now it only uses 64 bytes so using parson on platforms with little memory shouldn't be problematic anymore.
