### ISSUE TITLE
Feature request: support for comments

### ISSUE THREAD

**Issue by sylvain-miermont** [kgabis/parson#9]
Would it be possible for parson to support at least one of the comment styles bellow ?
- suspend parsing from /\* to */
- suspend parsing from // to newline
- suspend parsing from # to newline

Comment are not part of the JSON specification but they are an invaluable tool when using JSON for configuration files, on when providing an example JSON data structure to another developer.

**Comment by richardtomkins** [comment]
This feature, parsing invalid JSON files with "C" type comments included, vexes me most extremely.

I use various JSON validators to verify the production of JSON files and the presence of comments in these JSON files makes the validators puke.

There is a standard, [RFC 7159](https://tools.ietf.org/html/rfc7159), and comments are not part of JSON.
As well, [Introducing JSON](http://www.json.org/), does not include comments in its explanation.
