### ISSUE TITLE
Documentation: when does serialisation include trailing \0?

### ISSUE THREAD

**Issue by lindig** [kgabis/parson#94]
I'd like to understand how trailing \0 are handled by the serialisation functions:

```
size_t      json_serialization_size(const JSON_Value *value); /* returns 0 on fail */
JSON_Status json_serialize_to_buffer(const JSON_Value *value, char *buf, size_t buf_size_in_bytes);
JSON_Status json_serialize_to_file(const JSON_Value *value, const char *filename);
char *      json_serialize_to_string(const JSON_Value *value);
```

Is `json_serialization_size` including a trailing \0? What is the correct size of the buffer to fit the output completely? I believe a few words in the header file would be helpful. I suspect that ` json_serialization_size` does not include a trailing \0 but the string returned by `json_serialize_to_string` does contain a \0 and thus would be size+1 bytes long.

**Comment by mbelicki** [comment]
Writing that issue probably took 10 times more time than actually looking at the source code. Spoiler alert: your assumptions are wrong.

**Comment by kgabis** [comment]
Of course it's size in bytes including a trailing \0 (unlike C's strlen).
