### ISSUE TITLE
strtod is locale dependent

### ISSUE THREAD

**Issue by rib** [kgabis/parson#98]
In particular for a lot of people the `decimal_point` may be a comma `,` instead of a period `.` whereas I think parson should ideally ensure numbers are consistently parsed as ascii and only expecting a period. Maybe parson could use [`strtod_l`](http://www.manpagez.com/man/3/strtod_l/) when available and parse numbers with the `"C"` locale.

**Comment by janoosthoek** [comment]
easy to reproduce and test (taken from an IoT hub example):
JSON_Value* v = json_parse_string("{\"softwareVersion\":1, \"reported_maxSpeed\":100, \"vanityPlate\":\"1I1\"}");


This will simply fail when the locale is using a ',' decimal separator. Below is my code *hack* to make it work. I don't like this static approach (thread-safe/leak) …


Maybe there is another way, but if someone is stuck like me.. then at least this will get them going on a GNU compiler.



`
#define _GNU_SOURCE // needed to unlock the strtod_l 
#include <locale.h>
#include <stdlib.h>


// Cache locale object
static int c_locale_initialized = 0;
static locale_t c_locale;

locale_t get_c_locale()
{
  if(!c_locale_initialized)
  {
    c_locale_initialized = 1;
    c_locale = newlocale(LC_ALL_MASK, "C", NULL);
  }
  return c_locale;
}

static JSON_Value * parse_number_value(const char **string) {
    char *end;
    double number = 0;
    errno = 0;
    
    number = strtod_l(*string, &end, get_c_locale()); // use locale independent version.
    if (errno || !is_decimal(*string, end - *string)) {
        return NULL;
    }
    *string = end;
    printf("parse_number_value %s %f \n", *string, number);
    return json_value_init_number(number);
}
`

**Comment by coolgeek6667** [comment]
in addition, serializing to a buffer is affected as well; E.g. 1234.56 could get serialized to `{"num":1'234,56}` since `sprintf` is used.

**Comment by kgabis** [comment]
I don't see a good way of fixing this issue. Locales are implemented in different ways on various systems so it's a real pita to implement a workaround and I don't want to provide a custom strtod and sprintf. The best way of fixing this from user's perspective is using setlocale.
